create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'client_status') then
    create type public.client_status as enum (
      'contacted',
      'proposed',
      'negotiating',
      'active',
      'paused',
      'ended'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'channel_type') then
    create type public.channel_type as enum (
      'xiaohongshu',
      'dianping',
      'douyin'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'contact_status') then
    create type public.contact_status as enum (
      'active',
      'inactive',
      'blocked'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'settlement_status') then
    create type public.settlement_status as enum (
      'pending',
      'done'
    );
  end if;
end $$;

create table if not exists public.admins (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null,
  email text not null unique,
  company text,
  title text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

create table if not exists public.client_options (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('category', 'sales_region', 'product')),
  value text not null,
  created_at timestamptz not null default now(),
  unique (kind, value)
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  company_name text not null unique,
  contact_person text,
  phone text,
  email text,
  status public.client_status not null default 'contacted',
  contract_start date,
  contract_end date,
  contract_amount numeric(14, 2),
  memo text,
  manager_id uuid references public.admins (id) on delete set null,
  manager_name text,
  contract_file_path text,
  postal_code text,
  region text,
  sales_region text,
  district text,
  road_address text,
  building_detail text,
  category text,
  first_contact_date date,
  contract_product text,
  owner_id uuid references public.admins (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.influencers (
  id bigint generated by default as identity primary key,
  channel public.channel_type not null default 'xiaohongshu',
  handle text not null unique,
  followers integer not null default 0,
  account_url text,
  unit_price numeric(14, 2),
  memo text,
  name_en text,
  bank_name text,
  branch_name text,
  account_number text,
  phone text,
  postal_code text,
  prefecture text,
  city text,
  street text,
  contact_status public.contact_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_clients_status on public.clients (status);
create index if not exists idx_clients_owner_id on public.clients (owner_id);
create index if not exists idx_influencers_channel on public.influencers (channel);
