begin;

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'client_status') then
    create type public.client_status as enum (
      'contacted',
      'proposed',
      'negotiating',
      'active',
      'paused',
      'ended'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'channel_type') then
    create type public.channel_type as enum (
      'xiaohongshu',
      'dianping',
      'douyin'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'contact_status') then
    create type public.contact_status as enum (
      'active',
      'inactive',
      'blocked'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'settlement_status') then
    create type public.settlement_status as enum (
      'pending',
      'done'
    );
  end if;
end $$;

create table if not exists public.admins (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null,
  email text not null unique,
  company text,
  title text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

create table if not exists public.client_options (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('category', 'sales_region', 'product')),
  value text not null,
  created_at timestamptz not null default now(),
  unique (kind, value)
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  company_name text not null unique,
  contact_person text,
  phone text,
  email text,
  status public.client_status not null default 'contacted',
  contract_start date,
  contract_end date,
  contract_amount numeric(14, 2),
  monthly_management_fee numeric(14, 2),
  memo text,
  manager_id uuid references public.admins (id) on delete set null,
  manager_name text,
  contract_file_path text,
  postal_code text,
  region text,
  sales_region text,
  district text,
  road_address text,
  building_detail text,
  category text,
  first_contact_date date,
  contract_product text,
  owner_id uuid references public.admins (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.influencers (
  id bigint generated by default as identity primary key,
  channel public.channel_type not null default 'xiaohongshu',
  handle text not null unique,
  followers integer not null default 0,
  account_url text,
  unit_price numeric(14, 2),
  memo text,
  name_en text,
  bank_name text,
  branch_name text,
  account_number text,
  phone text,
  postal_code text,
  prefecture text,
  city text,
  street text,
  contact_status public.contact_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  scheduled_at timestamptz,
  client_id bigint not null references public.clients (id) on delete cascade,
  influencer_id bigint not null references public.influencers (id) on delete cascade,
  progress_status text not null default 'recruiting'
    check (progress_status in ('recruiting', 'recruited', 'preparing', 'upload_waiting', 'uploaded', 'delayed', 'canceled')),
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  schedule_id bigint unique references public.schedules (id) on delete set null,
  client_id bigint not null references public.clients (id) on delete cascade,
  influencer_id bigint not null references public.influencers (id) on delete cascade,
  post_url text,
  uploaded_on date,
  views integer not null default 0,
  likes integer not null default 0,
  comments integer not null default 0,
  shares integer not null default 0,
  settlement_status public.settlement_status not null default 'pending',
  settled_on date,
  payment_proof_path text,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_metrics_history (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  month text not null,
  views integer not null default 0,
  likes integer not null default 0,
  comments integer not null default 0,
  shares integer not null default 0,
  collected_at timestamptz,
  entered_at timestamptz,
  created_at timestamptz not null default now(),
  unique (post_id, month),
  check (month ~ '^\d{4}-\d{2}$')
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients (id) on delete cascade,
  year_month text not null,
  file_path text not null,
  file_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (client_id, year_month),
  check (year_month ~ '^\d{4}-\d{2}$')
);

create index if not exists idx_clients_status on public.clients (status);
create index if not exists idx_clients_owner_id on public.clients (owner_id);
create index if not exists idx_influencers_channel on public.influencers (channel);
create index if not exists idx_schedules_client_id on public.schedules (client_id);
create index if not exists idx_schedules_influencer_id on public.schedules (influencer_id);
create index if not exists idx_schedules_scheduled_at on public.schedules (scheduled_at);
create index if not exists idx_posts_client_id on public.posts (client_id);
create index if not exists idx_posts_influencer_id on public.posts (influencer_id);
create index if not exists idx_posts_settlement_status on public.posts (settlement_status);
create index if not exists idx_post_metrics_history_month on public.post_metrics_history (month);
create index if not exists idx_reports_client_id on public.reports (client_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_updated_at_admins on public.admins;
create trigger set_updated_at_admins
before update on public.admins
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_app_settings on public.app_settings;
create trigger set_updated_at_app_settings
before update on public.app_settings
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_clients on public.clients;
create trigger set_updated_at_clients
before update on public.clients
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_influencers on public.influencers;
create trigger set_updated_at_influencers
before update on public.influencers
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_schedules on public.schedules;
create trigger set_updated_at_schedules
before update on public.schedules
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_posts on public.posts;
create trigger set_updated_at_posts
before update on public.posts
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_reports on public.reports;
create trigger set_updated_at_reports
before update on public.reports
for each row execute function public.set_updated_at();

alter table public.admins enable row level security;
alter table public.app_settings enable row level security;
alter table public.client_options enable row level security;
alter table public.clients enable row level security;
alter table public.influencers enable row level security;
alter table public.schedules enable row level security;
alter table public.posts enable row level security;
alter table public.post_metrics_history enable row level security;
alter table public.reports enable row level security;

drop policy if exists "authenticated full access admins" on public.admins;
create policy "authenticated full access admins"
on public.admins
for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated full access app_settings" on public.app_settings;
create policy "authenticated full access app_settings"
on public.app_settings
for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated full access client_options" on public.client_options;
create policy "authenticated full access client_options"
on public.client_options
for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated full access clients" on public.clients;
create policy "authenticated full access clients"
on public.clients
for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated full access influencers" on public.influencers;
create policy "authenticated full access influencers"
on public.influencers
for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated full access schedules" on public.schedules;
create policy "authenticated full access schedules"
on public.schedules
for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated full access posts" on public.posts;
create policy "authenticated full access posts"
on public.posts
for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated full access post_metrics_history" on public.post_metrics_history;
create policy "authenticated full access post_metrics_history"
on public.post_metrics_history
for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated full access reports" on public.reports;
create policy "authenticated full access reports"
on public.reports
for all
to authenticated
using (true)
with check (true);

insert into storage.buckets (id, name, public)
values
  ('contracts', 'contracts', false),
  ('payments', 'payments', false),
  ('reports', 'reports', false)
on conflict (id) do nothing;

drop policy if exists "authenticated bucket access contracts" on storage.objects;
create policy "authenticated bucket access contracts"
on storage.objects
for all
to authenticated
using (bucket_id = 'contracts')
with check (bucket_id = 'contracts');

drop policy if exists "authenticated bucket access payments" on storage.objects;
create policy "authenticated bucket access payments"
on storage.objects
for all
to authenticated
using (bucket_id = 'payments')
with check (bucket_id = 'payments');

drop policy if exists "authenticated bucket access reports" on storage.objects;
create policy "authenticated bucket access reports"
on storage.objects
for all
to authenticated
using (bucket_id = 'reports')
with check (bucket_id = 'reports');

insert into public.app_settings (key, value)
values
  ('apify_actor_id', 'apify~instagram-post-scraper'),
  ('cny_to_krw_rate', '200')
on conflict (key) do update
set value = excluded.value,
    updated_at = now();

insert into public.client_options (kind, value)
values
  ('category', '뷰티'),
  ('category', '식음료'),
  ('category', '라이프스타일'),
  ('sales_region', '상하이'),
  ('sales_region', '베이징'),
  ('sales_region', '광저우'),
  ('product', '샤오홍슈 체험단'),
  ('product', '도우인 숏폼'),
  ('product', '따중디엔핑 매장 홍보')
on conflict (kind, value) do nothing;

commit;
