create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  scheduled_at timestamptz,
  client_id bigint not null references public.clients (id) on delete cascade,
  influencer_id bigint not null references public.influencers (id) on delete cascade,
  progress_status text not null default 'recruiting'
    check (progress_status in ('recruiting', 'recruited', 'preparing', 'upload_waiting', 'uploaded', 'delayed', 'canceled')),
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  schedule_id bigint unique references public.schedules (id) on delete set null,
  client_id bigint not null references public.clients (id) on delete cascade,
  influencer_id bigint not null references public.influencers (id) on delete cascade,
  post_url text,
  uploaded_on date,
  views integer not null default 0,
  likes integer not null default 0,
  comments integer not null default 0,
  shares integer not null default 0,
  settlement_status public.settlement_status not null default 'pending',
  settled_on date,
  payment_proof_path text,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_metrics_history (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  month text not null,
  views integer not null default 0,
  likes integer not null default 0,
  comments integer not null default 0,
  shares integer not null default 0,
  collected_at timestamptz,
  entered_at timestamptz,
  created_at timestamptz not null default now(),
  unique (post_id, month),
  check (month ~ '^\d{4}-\d{2}$')
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients (id) on delete cascade,
  year_month text not null,
  file_path text not null,
  file_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (client_id, year_month),
  check (year_month ~ '^\d{4}-\d{2}$')
);

create index if not exists idx_schedules_client_id on public.schedules (client_id);
create index if not exists idx_schedules_influencer_id on public.schedules (influencer_id);
create index if not exists idx_schedules_scheduled_at on public.schedules (scheduled_at);
create index if not exists idx_posts_client_id on public.posts (client_id);
create index if not exists idx_posts_influencer_id on public.posts (influencer_id);
create index if not exists idx_posts_settlement_status on public.posts (settlement_status);
create index if not exists idx_post_metrics_history_month on public.post_metrics_history (month);
create index if not exists idx_reports_client_id on public.reports (client_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_updated_at_admins on public.admins;
create trigger set_updated_at_admins
before update on public.admins
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_app_settings on public.app_settings;
create trigger set_updated_at_app_settings
before update on public.app_settings
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_clients on public.clients;
create trigger set_updated_at_clients
before update on public.clients
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_influencers on public.influencers;
create trigger set_updated_at_influencers
before update on public.influencers
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_schedules on public.schedules;
create trigger set_updated_at_schedules
before update on public.schedules
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_posts on public.posts;
create trigger set_updated_at_posts
before update on public.posts
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_reports on public.reports;
create trigger set_updated_at_reports
before update on public.reports
for each row execute function public.set_updated_at();
